// AUTO-GENERATED by scripts/gen-image-data.mjs from scripts/_image-fetch-report.json.
// Do not edit by hand — re-run the fetch + gen scripts to regenerate.
// Signature project images for the architect detail-page galleries. Every image
// carries visible attribution (photographer where known, publication, and a
// link to the original source) per the project's licensing requirements.

export interface ArchitectImage {
  /** Path under public/, relative to the deploy base. Wrap with link(). */
  src: string;
  width: number;
  height: number;
  /** Project name + year, shown under the image. */
  caption: string;
  /** Ready-to-render credit line (photographer / courtesy / via publication). */
  attribution: string;
  /** Photographer, when known (null otherwise). */
  credit: string | null;
  /** Link to the original source page for the image. */
  sourceUrl: string;
}

export const architectImages: Record<string, ArchitectImage[]> = {
  "nick-deaver": [
    {
      "src": "images/architects/nick-deaver/1.jpg",
      "width": 1200,
      "height": 892,
      "caption": "RaveOn (2018)",
      "attribution": "Photo © Casey Dunn · via ArchDaily",
      "credit": "Casey Dunn",
      "sourceUrl": "https://www.archdaily.com/967565/raveon-nick-deaver-architect"
    },
    {
      "src": "images/architects/nick-deaver/2.jpg",
      "width": 1200,
      "height": 1000,
      "caption": "RaveOn (2018)",
      "attribution": "Photo © Casey Dunn · via ArchDaily",
      "credit": "Casey Dunn",
      "sourceUrl": "https://www.archdaily.com/967565/raveon-nick-deaver-architect"
    },
    {
      "src": "images/architects/nick-deaver/3.jpg",
      "width": 1200,
      "height": 922,
      "caption": "RaveOn (2018)",
      "attribution": "Photo © Casey Dunn · via ArchDaily",
      "credit": "Casey Dunn",
      "sourceUrl": "https://www.archdaily.com/967565/raveon-nick-deaver-architect"
    }
  ],
  "matt-fajkus": [
    {
      "src": "images/architects/matt-fajkus/1.jpg",
      "width": 1200,
      "height": 752,
      "caption": "Split House (2019)",
      "attribution": "Courtesy Matt Fajkus Architecture",
      "credit": null,
      "sourceUrl": "https://www.mfarchitecture.com/work-split-house"
    },
    {
      "src": "images/architects/matt-fajkus/2.jpg",
      "width": 1200,
      "height": 816,
      "caption": "Re-Open House (2017)",
      "attribution": "Courtesy Matt Fajkus Architecture",
      "credit": null,
      "sourceUrl": "https://www.mfarchitecture.com/work-reopen-house"
    },
    {
      "src": "images/architects/matt-fajkus/3.jpg",
      "width": 1200,
      "height": 923,
      "caption": "Inverse House",
      "attribution": "Courtesy Matt Fajkus Architecture",
      "credit": null,
      "sourceUrl": "https://www.mfarchitecture.com/work-inverse-house"
    }
  ],
  "webber-studio": [
    {
      "src": "images/architects/webber-studio/1.jpg",
      "width": 1200,
      "height": 788,
      "caption": "Fairfield House",
      "attribution": "Courtesy Webber + Studio",
      "credit": null,
      "sourceUrl": "https://webberstudio.com/wp-content/uploads/2021/05/fairfield-house7-1.jpg"
    },
    {
      "src": "images/architects/webber-studio/2.jpg",
      "width": 1200,
      "height": 801,
      "caption": "Angelwylde Residence",
      "attribution": "Courtesy Webber + Studio",
      "credit": null,
      "sourceUrl": "https://webberstudio.com/wp-content/uploads/2021/05/angelwylde-residence15-1.jpg"
    },
    {
      "src": "images/architects/webber-studio/3.jpg",
      "width": 1024,
      "height": 683,
      "caption": "Woodland Residence",
      "attribution": "Courtesy Webber + Studio",
      "credit": null,
      "sourceUrl": "https://webberstudio.com/wp-content/uploads/2021/05/Woodland-Residences-7-1.jpg"
    }
  ],
  "a-parallel": [
    {
      "src": "images/architects/a-parallel/1.jpg",
      "width": 1200,
      "height": 796,
      "caption": "Three Courts Residence",
      "attribution": "Courtesy A Parallel Architecture",
      "credit": null,
      "sourceUrl": "https://www.aparallel.com/three-courts-residence"
    },
    {
      "src": "images/architects/a-parallel/2.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Terrace Mountain Residence",
      "attribution": "Courtesy A Parallel Architecture",
      "credit": null,
      "sourceUrl": "https://www.aparallel.com/terrace-mountain-residence"
    }
  ],
  "pollen": [
    {
      "src": "images/architects/pollen/1.jpg",
      "width": 1200,
      "height": 1340,
      "caption": "Balcones House (2011)",
      "attribution": "Photo © Whit Preston · via ArchDaily",
      "credit": "Whit Preston",
      "sourceUrl": "https://www.archdaily.com/805995/balcones-house-pollen-architecture-and-design"
    },
    {
      "src": "images/architects/pollen/2.jpg",
      "width": 1200,
      "height": 1200,
      "caption": "Balcones House (2011)",
      "attribution": "Photo © Casey Dunn · via ArchDaily",
      "credit": "Casey Dunn",
      "sourceUrl": "https://www.archdaily.com/805995/balcones-house-pollen-architecture-and-design"
    },
    {
      "src": "images/architects/pollen/3.jpg",
      "width": 1200,
      "height": 935,
      "caption": "Balcones House (2011)",
      "attribution": "Photo © Casey Dunn · via ArchDaily",
      "credit": "Casey Dunn",
      "sourceUrl": "https://www.archdaily.com/805995/balcones-house-pollen-architecture-and-design"
    }
  ],
  "clayton-korte": [
    {
      "src": "images/architects/clayton-korte/1.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Hill Country Wine Cave (2021)",
      "attribution": "Courtesy Clayton Korte",
      "credit": null,
      "sourceUrl": "https://claytonkorte.com/project/hill-country-wine-cave/"
    },
    {
      "src": "images/architects/clayton-korte/2.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Balcones Residence",
      "attribution": "Courtesy Clayton Korte",
      "credit": null,
      "sourceUrl": "https://claytonkorte.com/project/balcones-residence/"
    },
    {
      "src": "images/architects/clayton-korte/3.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Ridgecrest Residence",
      "attribution": "Courtesy Clayton Korte",
      "credit": null,
      "sourceUrl": "https://claytonkorte.com/project/ridgecrest-residence/"
    }
  ],
  "jay-corder": [
    {
      "src": "images/architects/jay-corder/1.jpg",
      "width": 1200,
      "height": 818,
      "caption": "Pemberton Residence",
      "attribution": "Courtesy Jay Corder, Architect",
      "credit": null,
      "sourceUrl": "https://www.jaycorder.com/projects/pemberton-residence/"
    },
    {
      "src": "images/architects/jay-corder/2.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Silver Ridge Residence",
      "attribution": "Courtesy Jay Corder, Architect",
      "credit": null,
      "sourceUrl": "https://www.jaycorder.com/projects/silver-ridge-residence/"
    },
    {
      "src": "images/architects/jay-corder/3.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Shoal Creek Residence",
      "attribution": "Courtesy Jay Corder, Architect",
      "credit": null,
      "sourceUrl": "https://www.jaycorder.com/projects/shoal-creek-residence/"
    }
  ],
  "specht-novak": [
    {
      "src": "images/architects/specht-novak/1.jpg",
      "width": 1200,
      "height": 675,
      "caption": "Stealth House (2024)",
      "attribution": "Courtesy Specht Novak",
      "credit": null,
      "sourceUrl": "https://spechtnovak.com/work/stealth-house/"
    },
    {
      "src": "images/architects/specht-novak/2.jpg",
      "width": 1200,
      "height": 900,
      "caption": "Zilker Park House",
      "attribution": "Courtesy Specht Novak",
      "credit": null,
      "sourceUrl": "https://spechtnovak.com/work/zilker-park-house/"
    },
    {
      "src": "images/architects/specht-novak/3.jpg",
      "width": 1200,
      "height": 762,
      "caption": "Treetops House",
      "attribution": "Courtesy Specht Novak",
      "credit": null,
      "sourceUrl": "https://spechtnovak.com/work/treetops-house/"
    }
  ],
  "jay-hargrave": [
    {
      "src": "images/architects/jay-hargrave/1.jpg",
      "width": 450,
      "height": 450,
      "caption": "Atelier Wong (2010)",
      "attribution": "via Dezeen",
      "credit": null,
      "sourceUrl": "https://www.dezeen.com/2010/01/05/atelier-wong-by-cottam-hargrave/"
    }
  ],
  "cuppett-kilpatrick": [
    {
      "src": "images/architects/cuppett-kilpatrick/1.jpg",
      "width": 1200,
      "height": 1200,
      "caption": "1 Hillside",
      "attribution": "via Dezeen",
      "credit": null,
      "sourceUrl": "https://www.dezeen.com/2017/03/22/tim-cuppett-architects-one-hillside-austin-home-modern-rustic-slurried-stone-charred-wood/"
    },
    {
      "src": "images/architects/cuppett-kilpatrick/2.jpg",
      "width": 1200,
      "height": 824,
      "caption": "Belmont Park (2019)",
      "attribution": "via Dwell",
      "credit": null,
      "sourceUrl": "https://www.dwell.com/home/belmont-park-1798d35c"
    }
  ],
  "chioco-design": [
    {
      "src": "images/architects/chioco-design/1.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Basin Ledge Residence",
      "attribution": "Courtesy Chioco Design",
      "credit": null,
      "sourceUrl": "https://www.chiocodesign.com/projects/basin-ledge-residence/"
    },
    {
      "src": "images/architects/chioco-design/2.jpg",
      "width": 1200,
      "height": 801,
      "caption": "Airole Residence",
      "attribution": "Courtesy Chioco Design",
      "credit": null,
      "sourceUrl": "https://www.chiocodesign.com/projects/airole-residence/"
    },
    {
      "src": "images/architects/chioco-design/3.jpg",
      "width": 880,
      "height": 713,
      "caption": "Rollingwood custom home",
      "attribution": "via HomeWorld Design",
      "credit": null,
      "sourceUrl": "https://homeworlddesign.com/custom-home-designed-chioco-design/"
    }
  ],
  "alterstudio": [
    {
      "src": "images/architects/alterstudio/1.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Barton Hills Residence",
      "attribution": "Courtesy Alterstudio Architecture",
      "credit": null,
      "sourceUrl": "https://alterstudio.net/work/barton-hills-residence"
    },
    {
      "src": "images/architects/alterstudio/2.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Westview Residence",
      "attribution": "Courtesy Alterstudio Architecture",
      "credit": null,
      "sourceUrl": "https://alterstudio.net/work/westview-residence"
    },
    {
      "src": "images/architects/alterstudio/3.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Tarrytown Residence",
      "attribution": "Courtesy Alterstudio Architecture",
      "credit": null,
      "sourceUrl": "https://alterstudio.net/work/tarrytown-residence"
    }
  ],
  "furman-keil": [
    {
      "src": "images/architects/furman-keil/1.jpg",
      "width": 1200,
      "height": 926,
      "caption": "Dog Run Ranch",
      "attribution": "Courtesy Furman + Keil Architects",
      "credit": null,
      "sourceUrl": "https://www.fkarchitects.net/dogrun-ranch"
    },
    {
      "src": "images/architects/furman-keil/2.jpg",
      "width": 1200,
      "height": 960,
      "caption": "Roost (2025)",
      "attribution": "Photo © Leonid Furmansky · via ArchDaily",
      "credit": "Leonid Furmansky",
      "sourceUrl": "https://www.archdaily.com/1032369/roost-platform-furman-plus-keil-architects"
    },
    {
      "src": "images/architects/furman-keil/3.jpg",
      "width": 1200,
      "height": 614,
      "caption": "Rammed Earth Ranch",
      "attribution": "Courtesy Furman + Keil Architects",
      "credit": null,
      "sourceUrl": "https://www.fkarchitects.net/rammed-earth-ranch"
    }
  ],
  "larue": [
    {
      "src": "images/architects/larue/1.jpg",
      "width": 600,
      "height": 600,
      "caption": "Hilltop renovation (2023)",
      "attribution": "via Dezeen",
      "credit": null,
      "sourceUrl": "https://www.dezeen.com/2023/07/18/larue-architects-kelle-contine-austin-house/"
    }
  ],
  "lake-flato": [
    {
      "src": "images/architects/lake-flato/1.jpg",
      "width": 1200,
      "height": 897,
      "caption": "Story Pool House",
      "attribution": "Courtesy Lake|Flato Architects",
      "credit": null,
      "sourceUrl": "https://www.lakeflato.com/ranches/story-pool-house"
    },
    {
      "src": "images/architects/lake-flato/2.jpg",
      "width": 1200,
      "height": 871,
      "caption": "Lake Austin House",
      "attribution": "Courtesy Lake|Flato Architects",
      "credit": null,
      "sourceUrl": "https://www.lakeflato.com/project/lake-austin-house/"
    },
    {
      "src": "images/architects/lake-flato/3.jpg",
      "width": 818,
      "height": 563,
      "caption": "Hillside House (2016)",
      "attribution": "via designboom",
      "credit": null,
      "sourceUrl": "https://www.designboom.com/architecture/lake-flato-hillside-house-austin-texas-07-01-2016/"
    }
  ],
  "andersson-wise": [
    {
      "src": "images/architects/andersson-wise/1.jpg",
      "width": 1200,
      "height": 630,
      "caption": "Lake House",
      "attribution": "Courtesy Andersson-Wise Architects",
      "credit": null,
      "sourceUrl": "https://www.anderssonwise.com/projects/lake-house"
    },
    {
      "src": "images/architects/andersson-wise/2.jpg",
      "width": 1200,
      "height": 630,
      "caption": "House Above Lake Austin",
      "attribution": "Courtesy Andersson-Wise Architects",
      "credit": null,
      "sourceUrl": "https://www.anderssonwise.com/projects/house-above-lake-austin"
    }
  ],
  "bercy-chen": [
    {
      "src": "images/architects/bercy-chen/1.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Edgeland House (2012)",
      "attribution": "Photo © Paul Bardagjy · via ArchDaily",
      "credit": "Paul Bardagjy",
      "sourceUrl": "https://www.archdaily.com/331677/edgeland-house-bercy-chen-studio"
    },
    {
      "src": "images/architects/bercy-chen/2.jpg",
      "width": 1200,
      "height": 800,
      "caption": "Edgeland House (2012)",
      "attribution": "Photo © Paul Bardagjy · via ArchDaily",
      "credit": "Paul Bardagjy",
      "sourceUrl": "https://www.archdaily.com/331677/edgeland-house-bercy-chen-studio"
    },
    {
      "src": "images/architects/bercy-chen/3.jpg",
      "width": 1200,
      "height": 927,
      "caption": "Annie Residence",
      "attribution": "via ArchDaily",
      "credit": null,
      "sourceUrl": "https://www.archdaily.com/250478/annie-residence-bercy-chen-studio"
    }
  ],
  "michael-hsu": [
    {
      "src": "images/architects/michael-hsu/1.jpg",
      "width": 1200,
      "height": 801,
      "caption": "Greenbelt Residence (2023)",
      "attribution": "Courtesy Michael Hsu Office of Architecture",
      "credit": null,
      "sourceUrl": "https://hsuoffice.com/catalogue/greenbelt-residence/"
    },
    {
      "src": "images/architects/michael-hsu/2.jpg",
      "width": 1200,
      "height": 862,
      "caption": "Llano Retreat",
      "attribution": "Courtesy Michael Hsu Office of Architecture",
      "credit": null,
      "sourceUrl": "https://hsuoffice.com/catalogue/llano-retreat/"
    }
  ]
};
